### ISSUE TITLE
MVP scope

### ISSUE THREAD

**Issue by Dunmail** [HL7-UK/UK-Core-Access#2]
Agree scope for MVP

Which of these questions are in scope?

Who is requesting information? e.g. Dr X, Practitioner at NHS Trust | Dr Scott, parent of Janette  
Who is the request about? e.g. Ms Janette Scott, NHS Number 4123456789
What endpoints are available? e.g. https://trust.nhs.uk/fhir
Can the endpoint provide information for a specific patient?
What types of information can the endpoint provide? e.g. Condition, MedicationStatement, Procedure
What information of each type does the endpoint hold for a specific patient?

**Comment by Dunmail** [comment]
# Scope
Consumer searches for Patient using identifier #7
Consumer retrieves information about the specific information types provided by the provider #8

# Consider for future scope
Consumer searches for Clinical information related to patient #9
Consumer searches for Patient using demographic information #5
Consumer searches for Clinical documents related to patient #10
Handling of sensitive or missing data
Security considerations e.g. requestor context

# Out of scope
Consumer searches for URL of FHIR servers supporting this capability

**Comment by clarotech** [comment]
Should the scope of UK-Core-Access be bound to a specific version of UK-Core profiles?
I assumed it was focussed initially on V 1.0.0 which would itself scope the different resource types that could be present within UK-Core-Access

**Comment by Dunmail** [comment]
If we include resource types that haven't been balloted then there is a risk that, when profiled, they are not compatible (e.g. this IG includes a search parameter where the field is subsequently excluded).

The IG will be limited to resource types that are within a balloted UK Core release.

The IG will not constrain implementers from making additional resource types available, but this is at their risk.
