### ISSUE TITLE
IHE QEDm as model for interaction

### ISSUE THREAD

**Issue by Dunmail** [HL7-UK/UK-Core-Access#4]
IHE have drafted a QEDm standard: https://wiki.ihe.net/index.php/Query_for_Existing_Data_for_Mobile_(QEDm) that defines a FHIR API for retrieval of patient information very similar to those that were identified during the discovery phase. Should we reference or align to this standard?
 
In addition, NHS Digital have a Clinical Data Sharing API under active development as part of UK Core [ 
https://simplifier.net/guide/uk-qepd?version=current] that was last updated in November 2022. @KevinMayfield: Is there a spec for international QEPD? Is this an 'official' NHS Digital project? How does it fit in with the prioritisation of work by the UK FHIR Board?

**Comment by clarotech** [comment]
I think we should assess QEDm to see whether there is anything overtly problematic with it. If not, then absolutely.

**Comment by clarotech** [comment]
Also might be an idea to look at PDQm as well. I recall reviewing this for IHE a few years back and it was a little US in focus, but I think that has been rectified now.

**Comment by KevinMayfield** [comment]
The NHS Digital spec is not official, it is more research looking at what is available (to support clinical process / FHIR Workflow)

We also had https://profiles.ihe.net/ITI/MHD/index.html (FHIR XDS) 
and https://wiki.ihe.net/index.php/Mobile_Retrieve_Form_for_Data_Capture to cover sharing data in other information models.

**Comment by Dunmail** [comment]
QEDm draft: https://www.ihe.net/uploadedFiles/Documents/PCC/IHE_PCC_Suppl_QEDm.pdf

**Comment by Dunmail** [comment]
QEDm-compatibility looks reasonable - review in more detail.

Also consider MHD, PDQm for future development.

**Comment by clarotech** [comment]
Having looked more closely at QEDm then I think the UK-Core-Access can probably support it (for the resources that are in the scope of UK-Core-Access).

QEDm by itself will not be sufficient by itself however, although not explicit it makes assumptions on the profiles that are used for the resources (think US Core !). These do not equally apply to UK Core, so additional searches will be required.
